$(document).ready(function(){
    $("#menu").click(function(){
        $(".dropdown").hide();
        $("nav").toggle("slow");
    });
    $("#services").click(function(){
        $(".dropdown").toggle();
    });
});